nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

packageExtensions:
  eslint-config-react-app@*:
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow':
        optional: true
      '@babel/plugin-transform-react-jsx':
        optional: true
  react-dev-utils@*:
    peerDependenciesMeta:
      '@testing-library/dom':
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.0.cjs
